create table application_statuses (id varchar2(255 char) not null, name varchar2(255 char) not null, type_code varchar2(255 char) not null, primary key (id));
create table applications (id varchar2(255 char) not null, final_diagnosis varchar2(255 char) not null, doctor_note_id varchar2(255 char) not null, parent_application_id varchar2(255 char), patient_id varchar2(255 char) not null, application_status_id varchar2(255 char) not null, primary key (id));
create table doctor_notes (id varchar2(255 char) not null, diagnosis varchar2(255 char) not null, institution_id varchar2(255 char) not null, primary key (id));
create table doctors (id varchar2(255 char) not null, first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, patronymic varchar2(255 char) not null, primary key (id));
create table favors (id varchar2(255 char) not null, name varchar2(255 char) not null, primary key (id));
create table institutions (id varchar2(255 char) not null, name varchar2(255 char) not null, primary key (id));
create table patients (id varchar2(255 char) not null, address varchar2(255 char) not null, birthdate date not null, first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, occupation varchar2(255 char) not null, patronymic varchar2(255 char) not null, phone_number varchar2(255 char) not null, primary key (id));
create table schedule_element_statuses (id varchar2(255 char) not null, name varchar2(255 char) not null, type_code varchar2(255 char) not null, primary key (id));
create table schedule_elements (id varchar2(255 char) not null, appointment_timestamp timestamp(6) not null, doctor_id varchar2(255 char) not null, favor_id varchar2(255 char) not null, status_id varchar2(255 char) not null, primary key (id));
create table scheduled_visits (id varchar2(255 char) not null, application_id varchar2(255 char) not null, schedule_element_id varchar2(255 char) not null, primary key (id));
create table unscheduled_visits (id varchar2(255 char) not null, appointment_timestamp timestamp(6) not null, commentary varchar2(255 char) not null, application_id varchar2(255 char) not null, doctor_id varchar2(255 char) not null, favor_id varchar2(255 char) not null, primary key (id));
alter table applications add constraint FKo0mwap5755ak27v5a0ye83hju foreign key (doctor_note_id) references doctor_notes;
alter table applications add constraint FK5de4n43kjp1loc1khakesvg5f foreign key (parent_application_id) references applications;
alter table applications add constraint FKg1l059h35j1wx83o0gc6spivl foreign key (patient_id) references patients;
alter table applications add constraint FKjfywm0w296a0a3l4l3p2ukh9b foreign key (application_status_id) references application_statuses;
alter table doctor_notes add constraint FKcfv5ph856l8tej1rhdwka4iqf foreign key (institution_id) references institutions;
alter table schedule_elements add constraint FK74vj75xs3avggwput0ct3naiq foreign key (doctor_id) references doctors;
alter table schedule_elements add constraint FKp3754sbn6q9mackrffm2lo9mq foreign key (favor_id) references favors;
alter table schedule_elements add constraint FK86ehf0nor8scxaaavlesve7wv foreign key (status_id) references schedule_element_statuses;
alter table scheduled_visits add constraint FK89h2rvysds3j9j5mft2qlauy6 foreign key (application_id) references applications;
alter table scheduled_visits add constraint FK2yqo8qi468dslap8c5seyn0fb foreign key (schedule_element_id) references schedule_elements;
alter table unscheduled_visits add constraint FKnkrs8r4trkcyjw4fk1awtj14e foreign key (application_id) references applications;
alter table unscheduled_visits add constraint FKfy4sc58vgfx5pxhdllkq2cpu5 foreign key (doctor_id) references doctors;
alter table unscheduled_visits add constraint FKrgjbw9fu6q9onpjynmww4duju foreign key (favor_id) references favors;
create table application_statuses (id varchar2(255 char) not null, name varchar2(255 char) not null, type_code varchar2(255 char) not null, primary key (id));
create table applications (id varchar2(255 char) not null, final_diagnosis varchar2(255 char) not null, doctor_note_id varchar2(255 char), patient_id varchar2(255 char) not null, status_id varchar2(255 char) not null, primary key (id));
create table doctor_notes (id varchar2(255 char) not null, diagnosis varchar2(255 char) not null, institution_id varchar2(255 char) not null, primary key (id));
create table doctors (id varchar2(255 char) not null, first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, patronymic varchar2(255 char), primary key (id));
create table favors (id varchar2(255 char) not null, name varchar2(255 char) not null, primary key (id));
create table institutions (id varchar2(255 char) not null, name varchar2(255 char) not null, primary key (id));
create table patients (id varchar2(255 char) not null, address varchar2(255 char), birthdate date not null, first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, occupation varchar2(255 char), patronymic varchar2(255 char), phone_number varchar2(255 char) not null, primary key (id));
create table schedule_element_statuses (id varchar2(255 char) not null, name varchar2(255 char) not null, type_code varchar2(255 char) not null, primary key (id));
create table schedule_elements (id varchar2(255 char) not null, appointment_timestamp timestamp(6) not null, comment varchar2(255 char), doctor_id varchar2(255 char) not null, favor_id varchar2(255 char) not null, status_id varchar2(255 char) not null, primary key (id));
alter table application_statuses add constraint UK_asg7nol5opu5hhsl1jewo2t3e unique (name);
alter table favors add constraint UK_nbxqsmkcje21sny1yf0krn358 unique (name);
alter table institutions add constraint UK_l3uewvcgggjpwyvk8gu8rs2b9 unique (name);
alter table applications add constraint FKo0mwap5755ak27v5a0ye83hju foreign key (doctor_note_id) references doctor_notes;
alter table applications add constraint FKg1l059h35j1wx83o0gc6spivl foreign key (patient_id) references patients;
alter table applications add constraint FKg2x3n6mbkw06w118r7da36xw9 foreign key (status_id) references application_statuses;
alter table doctor_notes add constraint FKcfv5ph856l8tej1rhdwka4iqf foreign key (institution_id) references institutions;
alter table schedule_elements add constraint FK74vj75xs3avggwput0ct3naiq foreign key (doctor_id) references doctors;
alter table schedule_elements add constraint FKp3754sbn6q9mackrffm2lo9mq foreign key (favor_id) references favors;
alter table schedule_elements add constraint FK86ehf0nor8scxaaavlesve7wv foreign key (status_id) references schedule_element_statuses;
create table application_statuses (id varchar2(255 char) not null, name varchar2(255 char) not null, type_code varchar2(255 char) not null, primary key (id));
create table applications (id varchar2(255 char) not null, final_diagnosis varchar2(255 char) not null, doctor_note_id varchar2(255 char), patient_id varchar2(255 char) not null, status_id varchar2(255 char) not null, primary key (id));
create table doctor_notes (id varchar2(255 char) not null, diagnosis varchar2(255 char) not null, institution_id varchar2(255 char) not null, primary key (id));
create table doctors (id varchar2(255 char) not null, first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, patronymic varchar2(255 char), primary key (id));
create table favors (id varchar2(255 char) not null, name varchar2(255 char) not null, primary key (id));
create table institutions (id varchar2(255 char) not null, name varchar2(255 char) not null, primary key (id));
create table patients (id varchar2(255 char) not null, address varchar2(255 char), birthdate date not null, first_name varchar2(255 char) not null, last_name varchar2(255 char) not null, occupation varchar2(255 char), patronymic varchar2(255 char), phone_number varchar2(255 char) not null, primary key (id));
create table schedule_element_statuses (id varchar2(255 char) not null, name varchar2(255 char) not null, type_code varchar2(255 char) not null, primary key (id));
create table schedule_elements (id varchar2(255 char) not null, appointment_timestamp timestamp(6) not null, comment varchar2(255 char), doctor_id varchar2(255 char) not null, favor_id varchar2(255 char) not null, status_id varchar2(255 char) not null, primary key (id));
alter table application_statuses add constraint UK_asg7nol5opu5hhsl1jewo2t3e unique (name);
alter table favors add constraint UK_nbxqsmkcje21sny1yf0krn358 unique (name);
alter table institutions add constraint UK_l3uewvcgggjpwyvk8gu8rs2b9 unique (name);
alter table applications add constraint FKo0mwap5755ak27v5a0ye83hju foreign key (doctor_note_id) references doctor_notes;
alter table applications add constraint FKg1l059h35j1wx83o0gc6spivl foreign key (patient_id) references patients;
alter table applications add constraint FKg2x3n6mbkw06w118r7da36xw9 foreign key (status_id) references application_statuses;
alter table doctor_notes add constraint FKcfv5ph856l8tej1rhdwka4iqf foreign key (institution_id) references institutions;
alter table schedule_elements add constraint FK74vj75xs3avggwput0ct3naiq foreign key (doctor_id) references doctors;
alter table schedule_elements add constraint FKp3754sbn6q9mackrffm2lo9mq foreign key (favor_id) references favors;
alter table schedule_elements add constraint FK86ehf0nor8scxaaavlesve7wv foreign key (status_id) references schedule_element_statuses;
