server:
  port: 8116

spring:
  application:
    name: "rkib-appointment-server"
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
# Uncomment for database re-creation
#  jpa:
#    hibernate:
#      ddl-auto: create

springdoc:
  swagger-ui:
    path: /docs/api

application:
  endpoint:
    root: /api
    doctorNote: /doctorNotes
    doctor: /doctors
    institution: /institutions
    patient: /patients
    scheduleElement: /scheduleElements
    scheduleElementStatus: /scheduleElementStatuses
    favor: /favors
    application: /applications
    applicationStatus: /applicationStatuses
