server:
  port: 8116

spring:
  application:
    name: rkib-appointment-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_BEHAVIOUR}

springdoc:
  swagger-ui:
    path: /docs/api

application:
  endpoint:
    registration: /registration
    persons: /persons
  init:
    admin:
      email: ${ADMIN_USERNAME}
      password: ${ADMIN_PASSWORD}
