server:
  port: 8116

spring:
  application:
    name: rkib-appointment-backend
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_BEHAVIOUR}

springdoc:
  swagger-ui:
    path: /docs/api

application:
  default:
    adminUsername: ${ADMIN_USERNAME}
    adminPassword: ${ADMIN_PASSWORD}
  constant:
    defaultSort: id,asc
  baseApi: /api
  apiV1: /v1
  endpoint:
    people: /people
    patients: /patients
    employee: /employee
    procedures: /procedures
    institutions: /institutions
    appointmentStatuses: /appointmentStatuses
    scheduleStatuses: /scheduleStatuses
