server:
  port: 8116

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_BEHAVIOUR}
  jackson:
    dateFormat: dd.MM.yyyy

springdoc:
  swagger-ui:
    path: /docs/api

application:
  default:
    adminEmail: ${ADMIN_EMAIL}
    adminPassword: ${ADMIN_PASSWORD}
  constant:
    defaultSort: id,asc
  baseApi: /api
  apiV1: /v1
  endpoint:
    me: /me
    people: /people
    patients: /patients
    employees: /employees
    procedures: /procedures
    institutions: /institutions
    appointmentStatuses: /appointmentStatuses
    scheduleStatuses: /scheduleStatuses
    appointments: /appointments
    schedules: /schedules
